version: '2'
services:

  npm-install:
    image: meccg-node
    volumes:
      - .:/meccg
    command: |
      sh -c "npm install
             ./node_modules/.bin/bower --allow-root install"

  stylus-css:
    image: meccg-node
    volumes:
      - .:/meccg
    command: |
      sh -c "./node_modules/.bin/bower
             ./node_modules/.bin/stylus -w src/css -o resources/public/css/"

  lein-cljs:
    image: clojure:latest
    volumes:
      - .:/meccg
    ports:
      - 3449:3449
    command: |
      sh -c "cd /meccg
             lein cljsbuild auto dev"

  lein-meccg:
    image: clojure:latest
    volumes:
      - .:/meccg
    ports:
      - 1042:1042
    environment:
      MONGODB_HOST: mongodb
      ZMQ_HOST: "*"
    links:
      - mongodb
    depends_on:
      - mongodb
    command: |
      sh -c "cd /meccg
             lein deps
             lein fetch --no-card-images
             lein run dev"

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /tmp/meccg/mongo-data:/data/db
